/wazuh/wazuh-agent.tar.gz:
  size: 162993516
  sha: sha256:dcf9242ec871ba5b578a3a29041415ed35ef16f5976528fb49997aa605a42a46
/wazuh/wazuh-manager.tar.gz:
  size: 171339709
  sha: sha256:e178792f0b8782230fd98e5d055413ae2e7bc935972620e62929796ef307c352